# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Jesse Harrison Artwork"
subtitle:
author:
header:
 title: "Jesse Harrison Artwork"
 subtitle:
footer:
 name: "TBA"
 bio: "TBA2"
social_urls:
  twitter: "https://twitter.com/jessepharrison"
  instagram: "https://www.instagram.com/jessepat84"
  linkedin: "https://www.linkedin.com/in/jessepharrison"
  github: "https://github.com/jessepharrison"
