# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Jesse Harrison Artwork"
subtitle:
author: Jesse Harrison (2010 - 2021)
header:
 title: "Jesse Harrison Artwork"
 subtitle:
footer:
 name: "Jesse Harrison (* 1984, Finland)"
 bio: "I create photos and atmospheres with a focus on the space between visual art and music. Awards: 2018 Fine Art Photography Awards, Landscape Nominee | 2017 MonoVisions Photography Awards, Honourable Mention | 2015 Scottish Landscape Photographer of the Year, John Muir Trust Wild Places Prize"
social_urls:
  twitter: "https://twitter.com/jessepharrison"
  instagram: "https://www.instagram.com/jessepat84"
  linkedin: "https://www.linkedin.com/in/jessepharrison"
  github: "https://github.com/jessepharrison"
